---
  - name: "Insall Jenkins"
    hosts: deployer
    become: true
    vars:
      ansible_ssh_private_key_file: "/workspace/tf/infra/provision/access/deployment-ec2-key"
      jenkins_admin_password: "admin12345"
      jenkins_dev_password: "dev123"
      github_username: "atileren"
      github_password: '123Qaz!12'
      dockerhub_username: "atileren"
      dockerhub_password: '1qaz!QAZ'
            

    tasks:
    - shell: cat ~/.kube/config | grep certificate-authority-data | awk '{print $2}'
      register: ca_result
      delegate_to: 127.0.0.1
      become: false

    - set_fact:
        ca={{ ca_result.stdout }}

    - shell:  cat ~/.kube/config | grep server | awk '{print $2}'
      register: server_url_result
      delegate_to: 127.0.0.1
      become: false

    - set_fact:
        server_url={{ server_url_result.stdout }}

    - shell:  cat ~/.kube/config | grep current-context | awk '{print $2}'
      register: context_name_result
      delegate_to: 127.0.0.1
      become: false

    - set_fact:
        context_name={{ context_name_result.stdout }}

    - shell: "cat ~/.kube/config | grep 'cluster: '  | awk '{print $2}'"
      register: cluster_name_result
      delegate_to: 127.0.0.1
      become: false

    - set_fact:
        cluster_name={{ cluster_name_result.stdout }}
            
    - name: generate jenkins config file
      template:
        src: /workspace/ansible/jenkins/jenkins-casc.yaml.j2
        dest: /workspace/ansible/jenkins/jenkins-casc.yaml
      delegate_to: 127.0.0.1

    - name: generate pipeline file
      template:
        src: /workspace/ansible/jenkins/seedjob.groovy.j2
        dest: /workspace/ansible/jenkins/seedjob.groovy
      delegate_to: 127.0.0.1


    - name: create build directory
      file:
        path: /workspace/jenkins_build
        state: directory
        owner: root
        group: root
        mode: '0755'
        recurse: yes

    - name: copy Dockerfile
      copy:
        src: "{{ item }}"
        dest: /workspace/jenkins_build/
        owner: root
        group: root
        mode: '0644'
      with_fileglob:
      - /workspace/ansible/jenkins/*

    - name: build container image
      docker_image:
        name: jenkins-casc:v1.0
        build:
          path: /workspace/jenkins_build
        source: build
        state: present
 

    - name: Create jenkins container
      docker_container:
        name: jenkins-casc
        image: jenkins-casc:v1.0
        state: started
        recreate: yes
        published_ports:
          - 8080:8080 
        volumes: 
          - /var/run/docker.sock:/var/run/docker.sock
