---
  - name: "Insall Jenkins"
    hosts: deployer
    become: true
    vars:
      ansible_ssh_private_key_file: "/workspace/tf/infra/provision/access/deployment-ec2-key"
      jenkins_admin_password: ""
      jenkins_dev_password: ""
      github_username: ""
      github_password: ""
      dockerhub_username: ""
      dockerhub_password: ""
            

    tasks:
    - name: generate jenkins config file
      template:
        src: /workspace/ansible/jenkins/jenkins-casc.yaml.j2
        dst: /workspace/ansible/jenkins/jenkins-casc.yaml
      delegate_to: 127.0.0.1

    - name: generate pipeline file
      template:
        src: /workspace/ansible/jenkins/seedjob.groovy.j2
        dst: /workspace/ansible/jenkins/seedjob.groovy
      delegate_to: 127.0.0.1


    - name: create build directory
      file:
        path: /workspace/jenkins_build
        state: directory
        owner: root
        group: root
        mode: '0755'
        recurse: yes

    - name: copy Dockerfile
      copy:
        src: "{{ item }}"
        dest: /workspace/jenkins_build/
        owner: root
        group: root
        mode: '0644'
      with_fileglob:
      - /workspace/ansible/jenkins/*

    - name: build container image
      docker_image:
        name: jenkins-casc:v1.0
        build:
          path: /workspace/jenkins_build
        source: build
        state: present
 

    - name: Create nginx container
      docker_container:
        name: jenkins-casc
        image: jenkins-casc:v1.0
        state: started
        recreate: yes
        published_ports:
          - 8080:8080 
