---
  - name: "Insall Waypoint"
    hosts: deployer
    become: true
    vars:
      ansible_ssh_private_key_file: "/workspace/tf/infra/provision/access/deployment-ec2-key"

    tasks:
    - name: "Add the HashiCorp GPG key."
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present

    - name: set release variable
      shell: echo $(lsb_release -cs)
      register: release

    - set_fact:
        lsb={{ release.stdout }}

    - name: "Add the official HashiCorp Linux repository."
      apt_repository:
        repo: deb [arch=amd64] https://apt.releases.hashicorp.com {{ lsb }} main
        state: present
 
    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes

    - name: "Install requiered packages"
      apt:
        name:
          - waypoint
        state: present
